version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - SMI/reviewers
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - SMI/reviewers
  - package-ecosystem: maven
    directory: "/nlp/uk.ac.dundee.hic.nerd"
    schedule:
      interval: weekly
    reviewers:
      - SMI/reviewers
